services:
  - type: web
    name: tradr-server
    rootDir: tradr-server
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: FIREBASE_PROJECT_ID
        value: tradr-483b9
      - key: MONO_SECRET_KEY
        sync: false
      - key: MONO_WEBHOOK_SECRET
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
